# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_pf', '0003_keyset_alias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keyset',
            new_name='ApiKeyset',
        ),
        migrations.RenameField(
            model_name='apikeyset',
            old_name='apiSecret',
            new_name='apisecret',
        ),
    ]
